services:
  caddy:
    image: caddy:2.10.0
    
        condition: service_healthy
      postgres:
        condition: service_started
    restart: unless-stopped
    ports:
      - "3001:3001"

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${BASE_URL}
        NEXT_PUBLIC_CLOUD: ${CLOUD}
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DEMO=true
      - NEXT_PUBLIC_BACKEND_URL=${BASE_URL}
      - NEXT_PUBLIC_CLOUD=${CLOUD}
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3002:3002"

volumes:
  clickhouse-data:
  postgres-data:
  caddy_data:     # Persistent volume for Caddy's certificates and state
  caddy_config:   # Persistent volume for Caddy's configuration cache (optional but good practice)
