services:
  caddy:
    image: caddy:2.10.0
    container_name: caddy
    

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_PASSWORD=frog
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - 